// Package gents generates a single TypeScript file (types + an HTTP
// client) from a resolved apic contract, mirroring what internal/gen does
// for the Go server side — same ir.ContractIR, independent output.
package gents

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/0to1a/apic/internal/ir"
)

var pathParamRE = regexp.MustCompile(`\{([a-zA-Z0-9_]+)\}`)

// Generate renders a resolved contract into a single TypeScript file: one
// exported interface per struct (ctx-sourced middleware fields are never
// included — those are server-only), an ApiError class for the error
// envelope, and a createClient() factory with one async method per route.
// Callers are expected to have already run ir.Validate + ir.Resolve
// successfully.
func Generate(c *ir.ContractIR) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by apic. DO NOT EDIT.\n\n")

	for _, s := range c.Types {
		writeInterface(&b, s)
	}
	writeAPIError(&b)
	writeClient(&b, c)

	return []byte(b.String()), nil
}

// tsType maps an ir.GoType to its TypeScript spelling. int64 and float64
// (the contract's "int"/"num") both become "number" — TS has no separate
// integer type.
func tsType(t ir.GoType) string {
	switch t.Kind {
	case "string":
		return "string"
	case "int64", "float64":
		return "number"
	case "bool":
		return "boolean"
	case "named":
		return t.Name
	case "slice":
		return tsType(*t.Elem) + "[]"
	default:
		return "unknown"
	}
}

// writeInterface emits one `export interface Name { ... }` for s. Field
// names are quoted string-literal keys (not bare identifiers) so header
// names like "X-Client-Id" need no special-casing — every field, whatever
// its shape, renders and is accessed (see writeMethod) the same way.
func writeInterface(b *strings.Builder, s ir.StructIR) {
	fmt.Fprintf(b, "export interface %s {\n", s.Name)
	for _, f := range s.Fields {
		if f.Source == ir.SourceCtx {
			continue // middleware-provided context value, never seen by the client
		}
		opt, null := "", ""
		if f.Pointer {
			opt, null = "?", " | null"
		}
		fmt.Fprintf(b, "  %q%s: %s%s;\n", f.SourceName, opt, tsType(f.Type), null)
	}
	b.WriteString("}\n\n")
}

func writeAPIError(b *strings.Builder) {
	b.WriteString(`export class ApiError extends Error {
  code: string;
  httpStatus: number;
  details?: Record<string, unknown>;

  constructor(message: string, code: string, httpStatus: number, details?: Record<string, unknown>) {
    super(message);
    this.name = "ApiError";
    this.code = code;
    this.httpStatus = httpStatus;
    this.details = details;
  }
}

`)
}

func writeClient(b *strings.Builder, c *ir.ContractIR) {
	b.WriteString(`export function createClient(opts: {
  baseUrl?: string;
  headers?: () => HeadersInit;
  onError?: (e: ApiError) => void;
} = {}) {
  async function parseError(res: Response): Promise<ApiError> {
    const env = await res.json().catch(() => ({}) as Record<string, unknown>);
    return new ApiError(
      typeof env.message === "string" ? env.message : res.statusText,
      typeof env.status === "string" ? env.status : "UNKNOWN",
      res.status,
      env.details as Record<string, unknown> | undefined,
    );
  }

  return {
`)
	for _, r := range c.Routes {
		writeMethod(b, r)
	}
	b.WriteString(`  };
}
`)
}

// writeMethod emits one createClient() method for r, fully unrolled at
// codegen time from r.Request.Fields (each field's Source is already known,
// so there's no runtime tag-based dispatch — unlike apic.Bind on the Go
// side, which does need it since it works from a struct value, not IR).
func writeMethod(b *strings.Builder, r ir.RouteIR) {
	name := ir.Untitle(r.MethodName)
	returnType := "void"
	if r.ResponseType != "" {
		returnType = r.ResponseType
	}

	var query, header, body []ir.FieldIR
	for _, f := range r.Request.Fields {
		switch f.Source {
		case ir.SourceQuery:
			query = append(query, f)
		case ir.SourceHeader:
			header = append(header, f)
		case ir.SourceBody:
			body = append(body, f)
		}
	}

	fmt.Fprintf(b, "    async %s(req: %s): Promise<%s> {\n", name, r.Request.Name, returnType)
	fmt.Fprintf(b, "      let url = `${opts.baseUrl ?? \"\"}%s`;\n", pathExpr(r.Path))

	if len(query) > 0 {
		b.WriteString("      const searchParams = new URLSearchParams();\n")
		for _, f := range query {
			fmt.Fprintf(b, "      if (req[%q] !== undefined && req[%q] !== null) searchParams.set(%q, String(req[%q]));\n",
				f.SourceName, f.SourceName, f.SourceName, f.SourceName)
		}
		b.WriteString("      const qs = searchParams.toString();\n")
		b.WriteString("      if (qs) url += `?${qs}`;\n")
	}

	b.WriteString("      const headers = new Headers(opts.headers?.() ?? {});\n")
	if len(body) > 0 {
		b.WriteString("      headers.set(\"Content-Type\", \"application/json\");\n")
	}
	for _, f := range header {
		fmt.Fprintf(b, "      if (req[%q] !== undefined && req[%q] !== null) headers.set(%q, String(req[%q]));\n",
			f.SourceName, f.SourceName, f.SourceName, f.SourceName)
	}

	fmt.Fprintf(b, "      const res = await fetch(url, {\n        method: %q,\n        headers,\n", r.Method)
	if len(body) > 0 {
		b.WriteString("        body: JSON.stringify({\n")
		for _, f := range body {
			fmt.Fprintf(b, "          %q: req[%q],\n", f.SourceName, f.SourceName)
		}
		b.WriteString("        }),\n")
	}
	b.WriteString("      });\n")

	b.WriteString(`      if (!res.ok) {
        const err = await parseError(res);
        opts.onError?.(err);
        throw err;
      }
`)
	if r.ResponseType == "" {
		b.WriteString("    },\n")
		return
	}
	fmt.Fprintf(b, "      const env = await res.json();\n      return env.data as %s;\n    },\n", r.ResponseType)
}

// pathExpr turns a contract path ("/posts/{id}") into the body of a
// TypeScript template literal ("/posts/${encodeURIComponent(String(req[\"id\"]))}"),
// ready to be dropped between backticks.
func pathExpr(path string) string {
	return pathParamRE.ReplaceAllStringFunc(path, func(m string) string {
		name := m[1 : len(m)-1]
		return fmt.Sprintf("${encodeURIComponent(String(req[%q]))}", name)
	})
}
