// Code generated by apic. DO NOT EDIT.

export interface User {
  "id": string;
  "name": string;
}

export interface Page {
  "limit"?: number | null;
  "cursor"?: string | null;
}

export interface Post {
  "limit"?: number | null;
  "cursor"?: string | null;
  "id": string;
  "title": string;
}

export interface GetHealthRequest {
}

export interface GetHealthResponse {
  "status": string;
}

export interface PostLoginRequest {
  "username": string;
  "password": string;
}

export interface PostLoginResponse {
  "token": string;
}

export interface GetPostsRequest {
  "q"?: string | null;
  "limit"?: number | null;
  "cursor"?: string | null;
  "X-Client-Id"?: string | null;
}

export interface GetPostsResponse {
  "items": Post[];
  "next_cursor"?: string | null;
}

export interface GetPostsByIDRequest {
  "id": string;
}

export interface DeletePostsByIDRequest {
  "id": string;
}

export interface GetPostsByIDCommentsRequest {
  "id": string;
}

export interface GetPostsByIDCommentsResponse {
  "items": Post[];
}

export class ApiError extends Error {
  code: string;
  httpStatus: number;
  details?: Record<string, unknown>;

  constructor(message: string, code: string, httpStatus: number, details?: Record<string, unknown>) {
    super(message);
    this.name = "ApiError";
    this.code = code;
    this.httpStatus = httpStatus;
    this.details = details;
  }
}

export function createClient(opts: {
  baseUrl?: string;
  headers?: () => HeadersInit;
  onError?: (e: ApiError) => void;
} = {}) {
  async function parseError(res: Response): Promise<ApiError> {
    const env = await res.json().catch(() => ({}) as Record<string, unknown>);
    return new ApiError(
      typeof env.message === "string" ? env.message : res.statusText,
      typeof env.status === "string" ? env.status : "UNKNOWN",
      res.status,
      env.details as Record<string, unknown> | undefined,
    );
  }

  return {
    async getHealth(req: GetHealthRequest): Promise<GetHealthResponse> {
      let url = `${opts.baseUrl ?? ""}/health`;
      const headers = new Headers(opts.headers?.() ?? {});
      const res = await fetch(url, {
        method: "GET",
        headers,
      });
      if (!res.ok) {
        const err = await parseError(res);
        opts.onError?.(err);
        throw err;
      }
      const env = await res.json();
      return env.data as GetHealthResponse;
    },
    async postLogin(req: PostLoginRequest): Promise<PostLoginResponse> {
      let url = `${opts.baseUrl ?? ""}/login`;
      const headers = new Headers(opts.headers?.() ?? {});
      headers.set("Content-Type", "application/json");
      const res = await fetch(url, {
        method: "POST",
        headers,
        body: JSON.stringify({
          "username": req["username"],
          "password": req["password"],
        }),
      });
      if (!res.ok) {
        const err = await parseError(res);
        opts.onError?.(err);
        throw err;
      }
      const env = await res.json();
      return env.data as PostLoginResponse;
    },
    async getPosts(req: GetPostsRequest): Promise<GetPostsResponse> {
      let url = `${opts.baseUrl ?? ""}/posts`;
      const searchParams = new URLSearchParams();
      if (req["q"] !== undefined && req["q"] !== null) searchParams.set("q", String(req["q"]));
      if (req["limit"] !== undefined && req["limit"] !== null) searchParams.set("limit", String(req["limit"]));
      if (req["cursor"] !== undefined && req["cursor"] !== null) searchParams.set("cursor", String(req["cursor"]));
      const qs = searchParams.toString();
      if (qs) url += `?${qs}`;
      const headers = new Headers(opts.headers?.() ?? {});
      if (req["X-Client-Id"] !== undefined && req["X-Client-Id"] !== null) headers.set("X-Client-Id", String(req["X-Client-Id"]));
      const res = await fetch(url, {
        method: "GET",
        headers,
      });
      if (!res.ok) {
        const err = await parseError(res);
        opts.onError?.(err);
        throw err;
      }
      const env = await res.json();
      return env.data as GetPostsResponse;
    },
    async getPostsByID(req: GetPostsByIDRequest): Promise<Post> {
      let url = `${opts.baseUrl ?? ""}/posts/${encodeURIComponent(String(req["id"]))}`;
      const headers = new Headers(opts.headers?.() ?? {});
      const res = await fetch(url, {
        method: "GET",
        headers,
      });
      if (!res.ok) {
        const err = await parseError(res);
        opts.onError?.(err);
        throw err;
      }
      const env = await res.json();
      return env.data as Post;
    },
    async deletePostsByID(req: DeletePostsByIDRequest): Promise<void> {
      let url = `${opts.baseUrl ?? ""}/posts/${encodeURIComponent(String(req["id"]))}`;
      const headers = new Headers(opts.headers?.() ?? {});
      const res = await fetch(url, {
        method: "DELETE",
        headers,
      });
      if (!res.ok) {
        const err = await parseError(res);
        opts.onError?.(err);
        throw err;
      }
    },
    async getPostsByIDComments(req: GetPostsByIDCommentsRequest): Promise<GetPostsByIDCommentsResponse> {
      let url = `${opts.baseUrl ?? ""}/posts/${encodeURIComponent(String(req["id"]))}/comments`;
      const headers = new Headers(opts.headers?.() ?? {});
      const res = await fetch(url, {
        method: "GET",
        headers,
      });
      if (!res.ok) {
        const err = await parseError(res);
        opts.onError?.(err);
        throw err;
      }
      const env = await res.json();
      return env.data as GetPostsByIDCommentsResponse;
    },
  };
}
